name: Build

on:
  push:
    branches: [ sdl_port ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix git safe directory
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global --add safe.directory /__w/skyland-beta/skyland-beta

      - name: Install prerequisites
        run: |
          brew update
          brew install cmake sdl2 sdl2_image python3
          pip3 install Pillow --break-system-packages
          curl -L https://github.com/libsdl-org/SDL/releases/download/release-2.32.10/SDL2-2.32.10.dmg > SDL2.dmg
          MOUNTDIR=$(echo `hdiutil mount SDL2.dmg | tail -1 \
          | awk '{$1=$2=""; print $0}'` | xargs -0 echo) \
          && ls "${MOUNTDIR}/
          && sudo cp -R "${MOUNTDIR}/"SDL2.framework /Library/Frameworks/ \
          && sudo chown -R root:wheel /Library/Frameworks/SDL2.framework \
          && sudo chmod -R 755 /Library/Frameworks/SDL2.framework
          
      - name: Build project
        run: |
          cd build
          cmake . -DGAMEBOY_ADVANCE=OFF
          make -j$(sysctl -n hw.ncpu)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyland-gba
          path: build/
          
