name: Build

on:
  push:
    branches: [ sdl_port ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix git safe directory
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global --add safe.directory /__w/skyland-beta/skyland-beta

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget tar bzip2 python3 python3-pip cmake libsdl2-dev 
          pip3 install pillow
          
      - name: Build project
        run: |
          cd build
          cmake . -DGAMEBOY_ADVANCE=OFF
          make -j

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyland-gba
          path: build/
          
